# Development / Test environment for Tablo

services:
  tablo-master:
    image: ${reg}/tablo-full:latest
    build:
      context: .
      dockerfile: prod.Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command:
      - /tablo-full/bin/tablo_master
    networks:
      - tablo-network
  tablo-node:
    image: ${reg}/tablo-full:latest
    build:
      context: .
      dockerfile: prod.Dockerfile
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

    command:
      - /tablo-full/bin/tablo_node
    networks:
      - tablo-network
networks:
  tablo-net:
    driver: bridge
