// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lib/libtabnet/src/protobuf/transfere_protocol.proto
// Protobuf C++ Version: 6.31.1

#include "lib/libtabnet/src/protobuf/transfere_protocol.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace transfereprotocol {

inline constexpr SerializedPacket::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        method_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SerializedPacket::SerializedPacket(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SerializedPacket_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SerializedPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SerializedPacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SerializedPacketDefaultTypeInternal() {}
  union {
    SerializedPacket _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SerializedPacketDefaultTypeInternal _SerializedPacket_default_instance_;
}  // namespace transfereprotocol
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_lib_2flibtabnet_2fsrc_2fprotobuf_2ftransfere_5fprotocol_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_lib_2flibtabnet_2fsrc_2fprotobuf_2ftransfere_5fprotocol_2eproto = nullptr;
const ::uint32_t
    TableStruct_lib_2flibtabnet_2fsrc_2fprotobuf_2ftransfere_5fprotocol_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::transfereprotocol::SerializedPacket, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::transfereprotocol::SerializedPacket, _impl_.method_),
        PROTOBUF_FIELD_OFFSET(::transfereprotocol::SerializedPacket, _impl_.payload_),
        1,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::transfereprotocol::SerializedPacket)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::transfereprotocol::_SerializedPacket_default_instance_._instance,
};
const char descriptor_table_protodef_lib_2flibtabnet_2fsrc_2fprotobuf_2ftransfere_5fprotocol_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n3lib/libtabnet/src/protobuf/transfere_p"
    "rotocol.proto\022\021transfereprotocol\"3\n\020Seri"
    "alizedPacket\022\016\n\006method\030\001 \001(\005\022\017\n\007payload\030"
    "\002 \001(\tb\010editionsp\350\007"
};
static ::absl::once_flag descriptor_table_lib_2flibtabnet_2fsrc_2fprotobuf_2ftransfere_5fprotocol_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_lib_2flibtabnet_2fsrc_2fprotobuf_2ftransfere_5fprotocol_2eproto = {
    false,
    false,
    138,
    descriptor_table_protodef_lib_2flibtabnet_2fsrc_2fprotobuf_2ftransfere_5fprotocol_2eproto,
    "lib/libtabnet/src/protobuf/transfere_protocol.proto",
    &descriptor_table_lib_2flibtabnet_2fsrc_2fprotobuf_2ftransfere_5fprotocol_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_lib_2flibtabnet_2fsrc_2fprotobuf_2ftransfere_5fprotocol_2eproto::offsets,
    file_level_enum_descriptors_lib_2flibtabnet_2fsrc_2fprotobuf_2ftransfere_5fprotocol_2eproto,
    file_level_service_descriptors_lib_2flibtabnet_2fsrc_2fprotobuf_2ftransfere_5fprotocol_2eproto,
};
namespace transfereprotocol {
// ===================================================================

class SerializedPacket::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SerializedPacket>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SerializedPacket, _impl_._has_bits_);
};

SerializedPacket::SerializedPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SerializedPacket_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:transfereprotocol.SerializedPacket)
}
PROTOBUF_NDEBUG_INLINE SerializedPacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::transfereprotocol::SerializedPacket& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        payload_(arena, from.payload_) {}

SerializedPacket::SerializedPacket(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SerializedPacket& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SerializedPacket_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SerializedPacket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.method_ = from._impl_.method_;

  // @@protoc_insertion_point(copy_constructor:transfereprotocol.SerializedPacket)
}
PROTOBUF_NDEBUG_INLINE SerializedPacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        payload_(arena) {}

inline void SerializedPacket::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.method_ = {};
}
SerializedPacket::~SerializedPacket() {
  // @@protoc_insertion_point(destructor:transfereprotocol.SerializedPacket)
  SharedDtor(*this);
}
inline void SerializedPacket::SharedDtor(MessageLite& self) {
  SerializedPacket& this_ = static_cast<SerializedPacket&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.payload_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SerializedPacket::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SerializedPacket(arena);
}
constexpr auto SerializedPacket::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SerializedPacket),
                                            alignof(SerializedPacket));
}
constexpr auto SerializedPacket::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SerializedPacket_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SerializedPacket::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SerializedPacket>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SerializedPacket::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SerializedPacket>(), &SerializedPacket::ByteSizeLong,
              &SerializedPacket::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SerializedPacket, _impl_._cached_size_),
          false,
      },
      &SerializedPacket::kDescriptorMethods,
      &descriptor_table_lib_2flibtabnet_2fsrc_2fprotobuf_2ftransfere_5fprotocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SerializedPacket_class_data_ =
        SerializedPacket::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SerializedPacket::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SerializedPacket_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SerializedPacket_class_data_.tc_table);
  return SerializedPacket_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 50, 2>
SerializedPacket::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SerializedPacket, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SerializedPacket_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::transfereprotocol::SerializedPacket>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string payload = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(SerializedPacket, _impl_.payload_)}},
    // int32 method = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SerializedPacket, _impl_.method_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(SerializedPacket, _impl_.method_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 method = 1;
    {PROTOBUF_FIELD_OFFSET(SerializedPacket, _impl_.method_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string payload = 2;
    {PROTOBUF_FIELD_OFFSET(SerializedPacket, _impl_.payload_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\42\0\7\0\0\0\0\0"
    "transfereprotocol.SerializedPacket"
    "payload"
  }},
};
PROTOBUF_NOINLINE void SerializedPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:transfereprotocol.SerializedPacket)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.payload_.ClearNonDefaultToEmpty();
  }
  _impl_.method_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SerializedPacket::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SerializedPacket& this_ = static_cast<const SerializedPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SerializedPacket::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SerializedPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:transfereprotocol.SerializedPacket)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 method = 1;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_method(), target);
  }

  // string payload = 2;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_payload();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "transfereprotocol.SerializedPacket.payload");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:transfereprotocol.SerializedPacket)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SerializedPacket::ByteSizeLong(const MessageLite& base) {
  const SerializedPacket& this_ = static_cast<const SerializedPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SerializedPacket::ByteSizeLong() const {
  const SerializedPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:transfereprotocol.SerializedPacket)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // string payload = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_payload());
    }
    // int32 method = 1;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_method());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SerializedPacket::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SerializedPacket*>(&to_msg);
  auto& from = static_cast<const SerializedPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:transfereprotocol.SerializedPacket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_internal_set_payload(from._internal_payload());
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.method_ = from._impl_.method_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SerializedPacket::CopyFrom(const SerializedPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:transfereprotocol.SerializedPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SerializedPacket::InternalSwap(SerializedPacket* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_, &other->_impl_.payload_, arena);
  swap(_impl_.method_, other->_impl_.method_);
}

::google::protobuf::Metadata SerializedPacket::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace transfereprotocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_lib_2flibtabnet_2fsrc_2fprotobuf_2ftransfere_5fprotocol_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
